# Generated by Django 4.1 on 2023-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_article_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="uniqueId",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
